### ISSUE TITLE
Aggregated on R-bloggers

### ISSUE THREAD

**Issue by kferris10** [timelyportfolio/buildingwidgets#29]
On your blog, it says that your blog is connected to R-bloggers, but I don't see it on the [list of contributing blogs](http://www.r-bloggers.com/blogs-list/)

**Comment by timelyportfolio** [comment]
Yes, for some reason, my humble little blog has not been accepted yet.  I filled out the request.

Maybe @talgalili knows why.

**Comment by timelyportfolio** [comment]
Will close in hopes that the newly discussed R blog aggregator eventually takes over.  Thx @kferris10

**Comment by talgalili** [comment]
Hi Timely, which of your blogs is not connected?

**Comment by timelyportfolio** [comment]
@talgalili http://buildingwidgets.com/blog .  Would appreciate getting on the list.  TimelyPortfolio is less active now that I have committed to building a `htmlwidget` each week :)

**Comment by talgalili** [comment]
o.k., I see two issues:
1) you didn't supply an RSS feed (nor can I find it from your blog)
2) In the posts - you are using base64 images instead of regular png. These cannot be aggregated. 

The solution is to have an rbloggers dedicated tag + feed, and make sure that in it, you will only give posts with png figures.
Can you make that work?
